apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
        - name: register-app
          image: zohaib56/register-app-pipeline:1.0.0-2
          ports:
            - containerPort: 8080
