apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
        - name: register-app
          image: zohaib56/register-app-pipeline:1.0.0-2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: register-app-service
spec:
  type: ClusterIP
  clusterIP: 10.0.0.2
  selector:
    app: register-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
